### PR TITLE
Collision meshes all model types

### PR DESCRIPTION
**Pull request by tomonorman**
if @azazdeaz  is happy with his testing, then we can merge and convert pre-existing models I think.

There is an issue on file size -> collision meshes generated can be rather large. Will make a separate issue on  this

### CODE REVIEW

**Comment by fabid** [comment]
> There is an issue on file size -> collision meshes generated can be rather large.

If the collision mesh is large, it sounds to me that we didn't simplify it enough?
What is a typical visual mesh size ? 50mb? if the collision mesh is a decimation, it should be around 10% of the visual mesh, in which case the 10% extra from the collision should not be too much of an issue?

**Review by azazdeaz — APPROVED** [review]
It's great that we have the dedicated collision mesh generation in place, and we can start experimenting with using them. We can iterate on optimizing the settings in future PRs.

**Comment by tomonorman** [comment]
The collision mesh size (relative to the visual) varies, but i've seen cases where its 3 - 4 times larger than the visual. Eg a visual mesh is 10mb and the collision is 40mb (in the case of a sack of potatoes), and from 300kb -> 800kb (an apple).

I would take a guess that much of this might come from the remeshing after the decimation (which i found to be helpful loading into gazebo), and might also be the use of triangles (in fbx) to smooth the collision surface out. As @azazdeaz mentions, now that we have the logic there, I think we can play around with the settings as we test and go forward

**Review by fabid — APPROVED** [review]

**Comment by fabid** [comment]
Thank you for the details. Still surprised, but if gazebo is happy, let's move forward and improve that later indeed

**Pull request merged**
