### PR TITLE
Extra model compatibility

### PR DESCRIPTION
**Pull request by tomonorman**
Does some better cleanup on error (a failed post request when uploading a model), and also (main event) removes shape keys from models allowing for a larger percentage of models to be have collision meshes applied. 

Shape keys (should) only really affect visual meshes, so there is hopefully little harm in removing them for  the collision portion

### CODE REVIEW

**Review by azazdeaz — APPROVED** [review]
Nice!! Thank you!

**Comment by fabid** [comment]
@tomonorman what is a shape key?

**Comment by tomonorman** [comment]
Its a saved modification to an object, that folks can then use to animate between (from 0 - 1). Different to a bone in that the keyshape is not an object. My understanding is that it thus often used for things like facial expressions.

**Comment by fabid** [comment]
Thank you for the explanation

**Pull request merged**
